# Generated by Django 5.2.6 on 2025-09-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_background_candidate_campaignhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('user_id', models.CharField(max_length=255)),
                ('timedate', models.DateTimeField(auto_now_add=True)),
                ('candidate_id', models.IntegerField()),
            ],
        ),
    ]
