# Generated by Django 5.2.6 on 2025-09-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='numopolars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='numoratings',
            field=models.IntegerField(default=0),
        ),
    ]
