# Generated by Django 5.2.6 on 2025-09-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_numopolars_candidate_numoratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='totalpolar',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='totalrating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='polarrating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='userrating',
            field=models.FloatField(default=0.0),
        ),
    ]
